Models/ErrorViewModel.cs
namespace Bincom_MVC_App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Property.cs
namespace Ebele
{
    public class Property
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime DateAdded { get; set; }

        public bool IsAvailable { get; set; }
    }
}

Models/SearchModel.cs
namespace Bincom_MVC_App.Models
{
    public class SearchModel
    {
        public int Id { get; set; }
    }
}

Controllers/HomeController.cs
using Bincom_MVC_App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bincom_MVC_App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PropertiesController.cs
using Bincom_MVC_App.Data;
using Ebele;
using Microsoft.AspNetCore.Mvc;

namespace Bincom_MVC_App.Controllers
{
    public class PropertiesController : Controller
    {
        public readonly BincomContext _dbConn;

        public PropertiesController(BincomContext dbConn)
        {
            _dbConn = dbConn;
        }

        public IActionResult Index()
        {
            var properties = _dbConn.Properties.ToList(); 
            return View(properties);
        }

        [HttpPost]
        public async Task<IActionResult> SingleProperty(int propertyId)
        {
            // fetch property from list of properties
            var singleProperty = _dbConn.Properties
                .Where(p => p.Id == propertyId)
                .FirstOrDefault();

            // return the property as a model in the view
            return View(singleProperty);
        }

        // Return Take Home After Tax#
        //private double ReturnTakeHomeAfterTax(double salary) => salary - 5000;
        private double ReturnTakeHomeAfterTax(double salary)
        {
            return salary - 5000;
        }

        private double ReturnTakeHomeAfterTax(int salary)
        {
            return salary - 5000;
        }

        private double ReturnTakeHomeAfterTax(float salary)
        {
            return salary - 5000;
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Ebele's Page</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLearnerApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebLearnerApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebLearnerApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebLearnerApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Properties/Index.cshtml
@using Ebele;
@{
    ViewData["Title"] = "Property Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Properties</h1>
    <p>Our properties will be shown below</p>
       
    @foreach (Property property in Model) 
    {
        <div class="prop">
            <h1>@property.Name</h1>
            <p>@property.Id</p>
            <p>@property.DateAdded</p>
        </div>
    }
    
    <h1>Search for a property by Id:</h1>
    @using (Html.BeginForm("SingleProperty", "Properties", FormMethod.Post))
    {
        <input name="propertyId" value="0" />
        <input type="submit" value="Find Property" />
    }

</div>

Views/Properties/SingleProperty.cshtml
@using Ebele;
@{
    ViewData["Title"] = "Single Property Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Properties</h1>
    <p>Our properties will be shown below</p>

    <ul>
        <li>My property is @Model.Id</li>
        <li>My property is @Model.Name</li>
        <li>My property is @Model.DateAdded</li>
    </ul>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bincom_MVC_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bincom_MVC_App.styles.css" asp-append-version="true" />
    <style>
        .prop {
            width: 300px; /* Set the width to 300px */
            padding-right: 10px; /* Add padding to the right */
            border: 1px solid grey; /* Set a grey border */
            float: left; /* Float the element to the left */
            height: 200px; /* Keep the height as per your original code */
            display: flex; /* Use flexbox for centering */
            justify-content: center; /* Center horizontally */
            align-items: center; /* Center vertically */
            text-align: center; /* Center text */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bincom_MVC_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="Index">Properties</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="SingleProperty?id=1">Single Property</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bincom_MVC_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>